### ISSUE TITLE
App for mac does not work

### ISSUE THREAD

**Issue by sobolevn** [electron-userland/electron-webpack-quick-start#1]
I have `git clone`d the project, installed all the dependencies.

`yarn dev` works as expected.

`yarn build` creates `.app` file, when tried to run it, this happened: 
<img width="643" alt="2017-09-09 13 51 28" src="https://user-images.githubusercontent.com/4660275/30239479-50f1e25a-9566-11e7-91d0-ec9ae7ab635a.png">

**Comment by develar** [comment]
Please provide `yarn build` code.

In this quick start there is `dist` task, but not `build`.

**Comment by sobolevn** [comment]
Sorry, `yarn dist`. I made no changes.

**Comment by develar** [comment]
Cannot reproduce.

**Comment by develar** [comment]
Please try to set electron-webpack version to 1.4.2

**Comment by sobolevn** [comment]
```
"electron-webpack": "^1.4.2",
```

Fixed it.

**Comment by develar** [comment]
Yeach.... Yarn bug. Yarn resolves x.x.x versions in the same way as 0.0.x

**Comment by develar** [comment]
Deps updated.
