### ISSUE TITLE
Add documentation regarding how to keep dependencies continuously updated

### ISSUE THREAD

**Issue by ryzokuken** [electron-userland/electron-webpack-quick-start#18]
I tried rebasing my own project on top of the latest master (this is an emergency as versions of electron older than `1.7.11` are insecure), and realized that I would have to take care of merge conflicts and what not, which might intimidate beginners. Perhaps the documentation should elaborate on how to keep these dependencies up to date?

![carbon](https://user-images.githubusercontent.com/13121330/35612951-7af6d880-0690-11e8-9720-98ec1377c22d.png)

**Comment by develar** [comment]
Simply "accept yours" and then call `npm-check-updates -a` (https://www.npmjs.com/package/npm-check-updates) to updates deps to latest.

**Comment by ryzokuken** [comment]
@develar great! That makes sense. Do you think this should be added to the documentation?

**Comment by develar** [comment]
The main goal of electron-webpack project — avoid boilerplates. It is a reason why there is `rm -rf .git` in the https://github.com/electron-userland/electron-webpack-quick-start#getting-started

This project is not a boilerplate. It is a quick-start, you simply copy it as is and nothing more. Nothing here to update and no need to update your app when this quick start project is changed (of course, you need to update dev/production dependencies regularly).

If it is not obvious from project description — PR is warmly welcome (to fix readme).

**Comment by ryzokuken** [comment]
I agree. My comment would have made more sense if it were a boilerplate, now that I think about it. Plus this is nothing specifically related to the project anyway, just general `npm` maintenance, so I guess you're right not to include it.
