### ISSUE TITLE
__static is not defined in production

### ISSUE THREAD

**Issue by dbradleyfl** [electron-userland/electron-webpack-quick-start#2]
## Steps for reproduction of issue
1. Cloned the boilerplate down and `yarn`
2. Only made the below code changes to src/main/index.js
3. Put an icon.png in static/
4. Works when `yarn dev`
5. `yarn run dist && open dist/electron-webpack-quick-start-0.0.0.dmg`
6. Open the app and throws __static is undefined

```
'use strict'

import { app, BrowserWindow, Tray } from 'electron'
import path from 'path'

const isDevelopment = process.env.NODE_ENV !== 'production'

// Global reference to mainWindow
// Necessary to prevent win from being garbage collected
let mainWindow
let tray
function createMainWindow () {
  tray = new Tray(path.join(__static, 'icon.png'))
```

**Comment by SimulatedGREG** [comment]
Quick fix...

**src/main/index.js (after `import`s)**
```js
if (process.env.NODE_ENV !== 'development') {
  global.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
}
```

**src/renderer/index.js (after `import`s)**
```js
if (process.env.NODE_ENV !== 'development') {
  window.__static = require('path').join(__dirname, '/static').replace(/\\/g, '\\\\')
}
```

Will be looking to fix in `electron-webpack`.
