### ISSUE TITLE
How can I embed my existing project?

### ISSUE THREAD

**Issue by imtiyazs** [electron-userland/electron-webpack-quick-start#5]
How can I embed my existing electron project in this template? I have 1 index.html and I have no idea how can I use it in the webpack template.

**Comment by develar** [comment]
Please see https://github.com/electron-userland/electron-webpack#quick-start

**Comment by imtiyazs** [comment]
Well, I read the whole documentation. It only says that the template doesnt require any html since it uses html webpack plugin. And I am really not sure how this works. But nvm, I managed to load my index html separately.
