### ISSUE TITLE
Can't pack with Tray bar icons

### ISSUE THREAD

**Issue by djalmaaraujo** [electron-userland/electron-webpack-quick-start#8]
I tried using ```__static```, using the icon in the root, but when I pack the application running `yarn dist`, the .asar file ignores the icon path and using ```__static``` brakes when starting the app:

The dist went ok with no errors.

<img width="532" alt="screenshot 2017-10-16 17 11 57" src="https://user-images.githubusercontent.com/3402/31622746-2a1a5e9a-b295-11e7-8803-ff8dbc4843a4.png">

Code:

```js
const mb = menubar({
  index: url,
  showDockIcon: true,
  icon: path.join(__static, '/IconTemplate.png'),
  alwaysOnTop: true
})

```

What can I do to explain more?

**Comment by develar** [comment]
Duplicate #4

Please see https://github.com/electron-userland/electron-webpack-quick-start/issues/4#issuecomment-334808384
