### ISSUE TITLE
The default value of app.allowRendererProcessReuse is deprecated

### ISSUE THREAD

**Issue by kiruh** [electron-userland/electron-webpack-quick-start#89]
When running `yarn dev`, electron outputs the following warning into terminal

> ┏ Electron -------------------
>
>  (electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
>
> ┗ ----------------------------

Any ideas on why it's happening and how to fix it?

**Comment by timohausmann** [comment]
Setting `app.allowRendererProcessReuse = true` on ready in index.js removes the warning for me.

```
// create main BrowserWindow when electron is ready
app.on('ready', () => {
  app.allowRendererProcessReuse = true
  mainWindow = createMainWindow()
})
```
